name: 🔁 Weekly Leadership Standup

on:
  workflow_dispatch:

  schedule:
    - cron: '0 13 * * 1'

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        run: |
              curl --location 'https://discord.com/api/v10/channels/${{ secrets.STL_LEADERSHIP_CHANNEL }}/messages' \
                  --header 'Content-Type: application/json' \
                  --header 'Accept: application/json' \
                  --header 'Authorization: Bot ${{ secrets.DISCORD_API_TOKEN }}' \
                  --data '{"content":"<@&492511881811197963>: **SHOW ME WHAT YOU GOT!**"}'
